import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#0066cc',
  white: '#ffffff',
  black: '#000000',
  lightGray: '#f5f5f5',
  border: '#e8e8e8',
  success: '#4caf50',
  danger: '#f44336',
  warning: '#ff9800',
  textDark: '#333333',
  textLight: '#666666',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.lightGray,
  },
  header: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  addButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 50,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  searchContainer: {
    backgroundColor: COLORS.white,
    marginHorizontal: 12,
    marginVertical: 8,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    fontSize: 14,
    color: COLORS.textDark,
  },
  listContent: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  banditCard: {
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginVertical: 6,
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  banditContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  banditPhoto: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.lightGray,
    marginRight: 12,
  },
  photoPlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  banditInfo: {
    flex: 1,
  },
  banditName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  banditSurnom: {
    fontSize: 12,
    color: COLORS.primary,
    fontStyle: 'italic',
    marginTop: 2,
  },
  banditEtat: {
    fontSize: 11,
    color: COLORS.warning,
    fontWeight: '600',
    marginTop: 2,
    paddingVertical: 2,
    paddingHorizontal: 6,
    backgroundColor: '#fff3e0',
    borderRadius: 4,
    alignSelf: 'flex-start',
  },
  banditDate: {
    fontSize: 11,
    color: COLORS.textLight,
    marginTop: 2,
  },
  banditActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    borderRadius: 6,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editButton: {
    backgroundColor: COLORS.primary,
  },
  detailButton: {
    backgroundColor: COLORS.warning,
  },
  deleteButton: {
    backgroundColor: COLORS.danger,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyStateText: {
    fontSize: 16,
    color: COLORS.textLight,
    marginTop: 12,
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '90%',
    paddingTop: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  modalBody: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  formGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textDark,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: 14,
    color: COLORS.textDark,
  },
  dateInput: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    gap: 10,
  },
  dateInputText: {
    fontSize: 14,
    color: COLORS.textDark,
    flex: 1,
  },
  button: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
  cancelButton: {
    backgroundColor: COLORS.lightGray,
  },
  cancelButtonText: {
    color: COLORS.textDark,
    fontSize: 14,
    fontWeight: '600',
  },
  saveButton: {
    backgroundColor: COLORS.primary,
  },
  saveButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '600',
  },
  detailModalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '95%',
    paddingTop: 16,
  },
  detailModalBody: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  detailModalFooter: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  detailPhotoContainer: {
    alignItems: 'center',
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  detailPhoto: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: COLORS.lightGray,
  },
  detailSection: {
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.primary,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailValue: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.textDark,
  },
  sexeValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  etatBadgeContainer: {
    marginTop: 4,
  },
  etatBadge: {
    fontSize: 14,
    fontWeight: '600',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    overflow: 'hidden',
    alignSelf: 'flex-start',
  },
  etatCapture: {
    backgroundColor: '#e3f2fd',
    color: COLORS.primary,
  },
  etatTransfert: {
    backgroundColor: '#fff3e0',
    color: COLORS.warning,
  },
  etatLibere: {
    backgroundColor: '#e8f5e9',
    color: COLORS.success,
  },
  infractionDetailList: {
    marginTop: 8,
    gap: 8,
  },
  infractionDetailItem: {
    flexDirection: 'row',
    backgroundColor: COLORS.lightGray,
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.danger,
  },
  infractionDetailContent: {
    flex: 1,
  },
  infractionDetailTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  infractionDetailDesc: {
    fontSize: 12,
    color: COLORS.textLight,
    marginTop: 4,
  },
  detailActionsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
    marginBottom: 16,
  },
  detailActionButton: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
  editDetailButton: {
    backgroundColor: COLORS.primary,
  },
  deleteDetailButton: {
    backgroundColor: COLORS.danger,
  },
  detailActionButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '600',
  },
  fabButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  photoContainer: {
    gap: 12,
  },
  photoPreview: {
    width: 150,
    height: 150,
    borderRadius: 8,
    backgroundColor: COLORS.lightGray,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  photoButtonsContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  photoButton: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
  cameraButton: {
    backgroundColor: COLORS.primary,
  },
  galleryButton: {
    backgroundColor: COLORS.warning,
  },
  photoButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '600',
  },
  stateContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  stateButton: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  stateButtonActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  stateButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  stateButtonTextActive: {
    color: COLORS.white,
  },
  sexeContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  sexeButton: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  sexeButtonActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  sexeButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  sexeButtonTextActive: {
    color: COLORS.white,
  },
  infractionNote: {
    fontSize: 12,
    color: COLORS.textLight,
    marginBottom: 8,
  },
  infractionList: {
    gap: 8,
  },
  infractionItem: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
  },
  infractionItemActive: {
    borderColor: COLORS.primary,
    backgroundColor: '#e3f2fd',
  },
  infractionCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
  },
  infractionContent: {
    flex: 1,
  },
  infractionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  infractionDescription: {
    fontSize: 12,
    color: COLORS.textLight,
    marginTop: 2,
  },
  datePickerView: {
    flex: 1,
    backgroundColor: COLORS.white,
    flexDirection: 'column',
  },
  datePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  datePickerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  datePickerHeaderButton: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.primary,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  datePickerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  datePickerContainer: {
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingVertical: 12,
  },
  photoViewerContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoViewerCloseButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 10,
  },
  photoViewerImage: {
    width: '100%',
    height: '70%',
  },
  photoViewerInfo: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  photoViewerName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.white,
  },
  photoViewerSurnom: {
    fontSize: 14,
    color: COLORS.lightGray,
    marginTop: 4,
    fontStyle: 'italic',
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
});
